config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  get '/inventories', to: 'inventories#index'
  get '/inventories/new', to: 'inventories#new'
  post '/inventories', to: 'inventories#create'
  get '/inventories/:id', to: 'inventories#show'
  delete '/inventories/:id', to: 'inventories#destroy'

  get '/inventories/:id/inventory_foods/new', to: 'inventory_foods#new'
  post '/inventories/:id/inventory_foods', to: 'inventory_foods#create'
  delete '/inventory_foods/:id', to: 'inventory_foods#destroy'
  resources :foods, only: %i[index show new create edit update destroy]
  resources :users
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  resources :general_shopping_list, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
          <% if current_user %>
            <li class="nav-item active">
          <%= link_to "Foods", foods_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>            </li>
            <li class="nav-item">
          <%= link_to "Inventories", inventories_path , class: "nav-link"%>
            </li>
            <% else %>
            <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
            <% end %>
        </ul>
    </div>
    <div class="mx-auto order-0">
      <%= link_to "RorRecipeApp", root_path, class: "nav-link" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ms-auto">
             <% if current_user %>
           <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path, class: "nav-link" %></li>
        <% end %>
        </ul>
    </div>
</nav>