config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  get '/inventories', to: 'inventories#index'
  get '/inventories/new', to: 'inventories#new'
  post '/inventories', to: 'inventories#create'
  get '/inventories/:id', to: 'inventories#show'
  delete '/inventories/:id', to: 'inventories#destroy'

  get '/inventories/:id/inventory_foods/new', to: 'inventory_foods#new'
  post '/inventories/:id/inventory_foods', to: 'inventory_foods#create'
  delete '/inventory_foods/:id', to: 'inventory_foods#destroy'
  resources :foods, only: %i[index show new create edit update destroy]
  resources :users
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  resources :general_shopping_list, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    redirect_to public_recipes_path unless current_user

    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.includes(:foods).find(params[:id])
    @user = @recipe.user
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @inventories = if current_user.nil?
                     []
                   else
                     current_user.inventories
                   end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    redirect_to public_recipes_path unless current_user

    recipe = Recipe.new(recipe_params)

    if recipe.save
      redirect_to recipe_path(recipe.id), notice: 'recipe successfully created'
    else
      redirect_to new_recipe_path, notice: 'recipe could not be created'
    end
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(public: !recipe.public)

    redirect_to recipe_path(recipe.id), notice: "The recipe is now #{recipe.public ? 'public' : 'private'}!"
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy!
    redirect_to recipes_path, notice: "Recipe #{recipe.name} deleted successfully!"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/-table.html.erb
<table class="table-auto w-full text-left mb-10 text-lg">
    <thead class="bg-gray-400">
      <tr class="h-10">
        <th class="p-4">Food</th>
        <th class="p-4">Measurement Unit</th>
        <th class="p-4">Value</th>
        <th class="p-4">Actions</th>
      </tr>
    </thead>
    <tbody class="bg-gray-300 p-20">
      <% @recipe.foods.each do |food| %>
        <tr class="h-16">
          <td class="p-4"><%= food.name %></td>
          <td class="p-4"><%= food.measurement_unit %></td>
          <td class="p-4">$<%= food.price %></td>
          <td class="p-4">
          <% if can? :manage, @recipe %>
            <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: RecipeFood.where(recipe_id: @recipe.id, food_id: food.id).first.id), class: 'underline' %> 
            <%= button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: RecipeFood.where(recipe_id: @recipe.id, food_id: food.id).first.id), method: :delete, class: 'underline'%>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/recipes/_recipe-card.html.erb
<li class="border border-black p-5 grid grid-cols-2 gap-y-4">
  <%= link_to recipe_path(recipe.id) do %>
    <h3><%= recipe.name %></h3>
  <% end %>
  <p><%= truncate recipe.description, length: 240 %></p>
  <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: 'hover:opacity-60 underline' if can? :destroy, recipe %>
</li>

app/views/recipes/_table.html.erb
<table class="table-auto w-full text-left mb-10 text-lg">
    <thead class="bg-gray-400">
      <tr class="h-10">
        <th class="p-4">Food</th>
        <th class="p-4">Measurement Unit</th>
        <th class="p-4">Value</th>
        <th class="p-4">Actions</th>
      </tr>
    </thead>
    <tbody class="bg-gray-300 p-20">
      <% @recipe.foods.each do |food| %>
        <tr class="h-16">
          <td class="p-4"><%= food.name %></td>
          <td class="p-4"><%= food.measurement_unit %></td>
          <td class="p-4">$<%= food.price %></td>
          <td class="p-4">
          <% if can? :manage, @recipe %>
            <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: RecipeFood.where(recipe_id: @recipe.id, food_id: food.id).first.id), class: 'underline' %> 
            <%= button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: RecipeFood.where(recipe_id: @recipe.id, food_id: food.id).first.id), method: :delete, class: 'underline'%>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  

app/views/recipes/index.html.erb
<div class="flex justify-between items-center mb-10 bg-slate-600 text-white">
  <h2 class="font-bold text-4x1 bg-slate-600 text-white">Recipes from <%= current_user.name %></h2>
  <%= link_to "Add new recipe", new_recipe_path %>
</div>
<ul class="flex flex-col gap-4 bg-slate-600 text-white">
<% @recipes.each do |recipe| %>
    <%= render partial: "recipe-card", locals: { recipe: recipe } %>
<% end %>
</ul>

app/views/recipes/new.html.erb
<h1 class="font-bold text-4xl mb-10 bg-slate-600 text-white">Create a new recipe</h1>
  <%= form_with model: @recipe, html: { class: 'flex flex-col gap-4 items-start bg-slate-600' } do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.text_field :name, placeholder: 'Recipe name' %>
    <%= f.number_field :preparation_time, placeholder: 'Preparation Time (minutes)' %>
    <%= f.number_field :cooking_time, placeholder: 'Cooking Time (minutes)' %>
    <%= f.text_area :description, placeholder: 'Description', size: '50x5'%>
    <div>
      <%= f.label :public, "Public" %>
      <%= f.check_box :public %>
    </div>
    <%= f.submit "Create recipe", class: 'border border-black p-2 rounded-lg cursor-pointer hover:opacity-60'%>
  <% end %>

app/views/recipes/show.html.erb
<h1 class="font-bold text-4xl mb-10 text-center bg-slate-600 text-white"><%= @recipe.name %></h1>
<div class="grid grid-cols-2 gap-y-4 mb-10 justify-items-start bg-slate-600 text-white">
  <h4 class="text-3xl">Preparation time: <span><%= @recipe.preparation_time %> minutes</span></h4>
  <div class="row-span-2 justify-self-center text-xl">
    This recipe is <span class="font-bold"><%= @recipe.public ? 'public' : 'Private' %></span>
    <% if can? :manage, @recipe %>
      <%= button_to "Make it #{@recipe.public ? 'private' : 'public'}", recipe_path(@recipe.id), class: 'underline', method: :patch %>
    <% end %>
  </div>
  <h4 class="text-3xl mb-10">Cooking time: <span><%= @recipe.cooking_time %> minutes</span></h4>
  <% if can? :manage, @recipe %>
    <%= link_to "Generate shopping list", '#', class: 'border border-black p-2 rounded-lg cursor-pointer hover:opacity-60', onclick: 'openModal()' %>
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'border border-black p-2 rounded-lg cursor-pointer justify-self-end hover:opacity-60' %>
  <% end %>
</div>
<% if @recipe.foods.present? %>
  <%= render "table" %>
<% end %>
<p class="bg-slate-600 text-white"><%= @recipe.description %></p>
<% if current_user %>
<%= link_to 'Back to recipes', recipes_path,class:"btn btn-primary" %>
<% else %>
<%= link_to 'Back to recipes', public_recipes_path,class:"btn btn-primary" %>
<% end %>



<div tabindex="-1" id="myModal" class="modal" style="display:none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Generating Shopping List</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <p >Choose an inventory to use</p>
         <%=form_with url: general_shopping_list_index_path, method: :get do |f| %>
      <div >
        <div>
          <%= f.select :inventory_id, @inventories.collect { |inventory| [inventory.name, inventory.id] }, :prompt => 'Select an Inventory', class: 'focus:outline-none', required: true %>
        </div>
        <%= f.hidden_field :recipe_id, value: @recipe.id, required: true %>
      </div>
      <div>
        <%= f.submit "Generate",class:"btn btn-primary text-black"  %>
      </div> 
    <% end %>
      </div>
      <div class="modal-footer">
        <span type="button" class="close btn btn-secondary text-black" data-bs-dismiss="modal">Close</span>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
var modal = document.getElementById("myModal");

var span = document.getElementsByClassName("close")[0];

let openModal = () => {
  modal.style.display = "block";
}

span.onclick = function() {
  modal.style.display = "none";
}
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>