config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  get '/inventories', to: 'inventories#index'
  get '/inventories/new', to: 'inventories#new'
  post '/inventories', to: 'inventories#create'
  get '/inventories/:id', to: 'inventories#show'
  delete '/inventories/:id', to: 'inventories#destroy'

  get '/inventories/:id/inventory_foods/new', to: 'inventory_foods#new'
  post '/inventories/:id/inventory_foods', to: 'inventory_foods#create'
  delete '/inventory_foods/:id', to: 'inventory_foods#destroy'
  resources :foods, only: %i[index show new create edit update destroy]
  resources :users
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  resources :general_shopping_list, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  # before_action :authenticate_member!

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.new(food_params)
    # @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <%= link_to food.name, food %>
  <%= food.measurement_unit %>
  <%= food.price %>
  <%= link_to "Edit", edit_food_path(food) %>
  <%= link_to "Delete", food, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :measurement_unit %>
  <%= form.text_field :measurement_unit %>

  <%= form.label :price %>
  <%= form.text_field :price %>
  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<section class="foods" >
<% if current_user %>
<div class="jumbotron bg-dark text-white" style="width:90%; margin:10px auto">
  <div class="container">
    <h1 class="display-4">Food List</h1>
    <p class="lead">You can display a list of food as in the wireframe.
   You can lead to the form that allows users to add new food..</p>
  </div>
</div>

<div class="text-center">
<%= link_to "Add food", new_food_path, class:"btn btn-primary btn-lg ms-auto",style:"margin:10px 10px;" %>

</div>
<table class="table table-dark" style="margin: 10px auto;width: 90%;">

  <thead>
   <tr>
        <th scope="col">Name</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
  </thead>
  <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td scope="row"><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td>
            <%= button_to "Delete", food_path(food.id), method: :delete %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>
<% else %>
<div class="jumbotron bg-dark text-white" style="width:90%; margin:10px auto">
  <div class="container">
    <h1 class="display-4">Food List</h1>
    <p class="lead">Only logged in users can see and edit foods. Feel free to have a look at the available public recipes</p>
  </div>
  <% end %>
</section>

app/views/foods/new.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg pb-10 px-10 pt-5">
    <div class="flex justify-start my-4">
      <%= link_to '< Foods', foods_path, class: 'text-gray-500' %>
    </div>

    <h1 class="text-2xl font-bold border-b-2">Add new food</h1>

    <% if @food.errors.any? %>
      <h2>The following errors prevented the food from being submitted</h2>
      <ul>
        <% @food.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    
    <div>
      <%= form_with(model: @food, local: true) do |f| %>
        <p class="mb-3 mt-5"> 
          <%= f.label :name, class: 'font-semibold pb-1' %><br />
          <%= f.text_field :name, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Food name'%>
        </p>

        <p class="mb-3"> 
          <%= f.label :measurement_unit, class: 'font-semibold pb-1' %><br />
          <%= f.text_field :measurement_unit, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'grams / units'%>
        </p>

        <p class="mb-3"> 
          <%= f.label :price, class: 'font-semibold pb-1' %><br />
          <%= f.text_field :price, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: '$ 0.00'%>
        </p>

        <p>
          <%= f.submit class: 'bg-orange-500 py-3 px-10 text-white hover:bg-orange-700 cursor-pointer' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>